# Generated by Django 3.1.5 on 2023-11-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
            ],
        ),
    ]
