# Generated by Django 3.1.5 on 2023-12-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_remove_employee_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
