# Generated by Django 3.1.5 on 2023-12-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_employee_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
            ],
        ),
    ]
